src/shopping/lists/api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.ShoppingListDetailAPIView.as_view(), 
            name='shopping_list_detail_api_view'),
    url(r'^(?P<pk>\d+)/items$', views.ShoppingItemsAPIView.as_view(), 
            name='shopping_items_api_view'),
    url(r'^add/$', views.AddShoppingListAPIView.as_view(), 
            name="add_shopping_list_api_view"),
    url(r'^add-item/$', views.AddShoppingItemAPIView.as_view(), 
            name="add_shopping_item_api_view"),
    url(r'^$', views.ShoppingListsAPIView.as_view(), 
            name="shopping_lists_api_view"),
]

src/shopping/lists/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.ShoppingListDetailView.as_view(),
            name='shopping_list_detail_view'),
    url(r'^(?P<pk>\d+)/delete/$', views.ShoppingListDeleteView.as_view(),
            name='shopping_list_delete_view'),
    url(r'^(?P<pk>\d+)/edit/$', views.EditShoppingListView.as_view(),
            name='edit_shopping_list_view'),
    url(r'^(?P<pk>\d+)/archive/$', views.ArchiveShoppingListView.as_view(),
            name='archive_shopping_list_view'),
    url(r'^(?P<pk>\d+)/add-items/$', views.AddItemsToListView.as_view(),
            name='add_items_to_list_view'),
    url(r'^(?P<pk>\d+)/delete-items/$', views.DeleteItemsFromListView.as_view(),
            name='delete_items_from_list_view'),
    url(r'^edit-items/$', views.EditItemsView.as_view(),
            name='edit_items_view'),
    url(r'^add/$', views.AddShoppingListView.as_view(),
            name="add_shopping_list_view"),
    url(r'^mark-items/$', views.MarkShoppingItemView.as_view(),
            name="mark_shopping_item_view"),
    url(r'^archive/$', views.ShoppingListsArchiveView.as_view(),
            name="shopping_lists_archive_view"),
    url(r'^search/$', views.ShoppingListsSearchView.as_view(),
            name='shopping_lists_search_view'),
    url(r'^$', views.ShoppingListsView.as_view(),
            name='shopping_lists_view'),
]

src/shopping/main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.MainPageView.as_view(), name='main_page_view'),
]

src/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^lists/', include('lists.urls', namespace="lists")),
    url(r'^items/', include('items.urls', namespace="items")),
    url(r'^charts/', include('charts.urls', namespace="charts")),
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace="main")),
    url(r'^api/lists/', include('lists.api.urls', namespace="lists_api")),
    url(r'^api/items/', include('items.api.urls', namespace="items_api")),
    url(r'^api/charts/', include('charts.api.urls', namespace="charts_api")),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shopping/lists/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse

from items.models import Item


class ShoppingList(models.Model):
    name = models.CharField(max_length=15)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shop = models.CharField(max_length=15)
    date = models.DateField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    archived = models.BooleanField(default=False)

    @property
    def shopping_items(self):
        shopping_items = ShoppingItem.objects.filter(shopping_list=self)
        return shopping_items

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('lists:shopping_list_detail_view', args=[str(self.pk)])

    class Meta:
        ordering = ['-date']


class ShoppingItem(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE,
                             null=True, blank=True)
    shopping_list = models.ForeignKey('ShoppingList', on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)
    bought = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-pk']


@receiver(pre_save, sender=ShoppingItem)
def default_name(sender, instance, *args, **kwargs):
    if not instance.name:
        instance.name = instance.item.name

src/shopping/lists/forms.py
from django import forms

from .models import ShoppingList


class ListCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ListCreateForm, self).__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': self.fields[field].label
            })
            if field == 'date':
                self.fields[field].widget.attrs.update(
                    {
                        'class': 'form-control datepicker',
                        'autocomplete': 'off',
                        'placeholder': self.fields[field].label,
                    }
                )

    class Meta:
        model = ShoppingList
        fields = ['name', 'shop', 'date']
        labels = {
            'name': 'List Name',
            'shop': 'Shop',
            'date': 'Date',
        }

src/shopping/lists/api/views.py
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    RetrieveAPIView,
    DestroyAPIView,
    RetrieveUpdateDestroyAPIView
    )

from lists.models import ShoppingList, ShoppingItem

from .serializers import (
    ShoppingListsSerializer,
    ShoppingListDetailSerializer,
    ShoppingListCreateSerializer,
    ShoppingItemSerializer,
    CreateShoppingItemSerializer
    )
from .permissions import IsOwner


class ShoppingListsAPIView(ListAPIView):
    serializer_class = ShoppingListsSerializer

    def get_queryset(self, *args, **kwargs):
        qs = ShoppingList.objects.filter(user=self.request.user)
        return qs


class AddShoppingListAPIView(CreateAPIView):
    serializer_class = ShoppingListCreateSerializer
    
    def get_queryset(self, *args, **kwargs):
        qs = ShoppingList.objects.filter(user=self.request.user)
        return qs

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class ShoppingListDetailAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = ShoppingListDetailSerializer
    permission_classes = (IsOwner,)

    def get_queryset(self, *args, **kwargs):
        qs = ShoppingList.objects.all()
        return qs


class ShoppingItemsAPIView(ListAPIView):
    serializer_class = ShoppingItemSerializer
    
    def get_queryset(self, *args, **kwargs):
        shopping_list = ShoppingList.objects.filter(user=self.request.user) \
                                            .get(pk=self.kwargs.get('pk'))
        qs = shopping_list.shoppingitem_set.all()
        return qs


class AddShoppingItemAPIView(CreateAPIView):
    serializer_class = CreateShoppingItemSerializer

src/shopping/lists/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.core.exceptions import PermissionDenied

from items.models import Item

from .models import ShoppingList, ShoppingItem
from .forms import ListCreateForm
from .decorators import user_is_list_owner, user_is_list_owner_via_item


class ShoppingListsView(LoginRequiredMixin, ListView):
    login_url = '/'
    redirect_field_name = 'redirect_to'

    template_name = 'lists/shopping_lists.html'
    context_object_name = 'shopping_lists'

    def get_queryset(self):
        return ShoppingList.objects.filter(user=self.request.user) \
            .filter(archived=False)


class ShoppingListsSearchView(LoginRequiredMixin, ListView):
    login_url = '/'
    redirect_field_name = 'redirect_to'

    template_name = 'lists/shopping_lists_search.html'
    context_object_name = 'shopping_lists'

    def get_queryset(self):
        q = self.request.GET.get('q')
        shopping_lists = ShoppingList.objects.filter(user=self.request.user) \
            .filter(archived=False)

        if q:
            shopping_lists = shopping_lists.filter(
                Q(name__icontains=q) |
                Q(shop__icontains=q)
                ).distinct()
        return shopping_lists


class ShoppingListsArchiveView(LoginRequiredMixin, ListView):
    login_url = '/'
    redirect_field_name = 'redirect_to'

    template_name = 'lists/shopping_lists_archive.html'
    context_object_name = 'shopping_lists'

    def get_queryset(self):
        return ShoppingList.objects.filter(user=self.request.user) \
            .filter(archived=True)


class ShoppingListDetailView(View):
    @method_decorator(login_required(login_url='users:login_view'))
    @user_is_list_owner
    def get(self, request, pk):
        template = 'lists/shopping_list_detail.html'
        shopping_list = get_object_or_404(ShoppingList, pk=pk)
        shopping_items = shopping_list.shopping_items

        sort_request = request.GET.get('sort_by')
        if sort_request == 'name':
            shopping_items = shopping_items.order_by('name')
        elif sort_request == 'category':
            shopping_items = shopping_items.order_by('item__category')
        elif sort_request == 'bought':
            shopping_items = shopping_items.order_by('bought')

        context = {
            'shopping_list': shopping_list,
            'shopping_items': shopping_items,
        }
        return render(request, template, context)


class ShoppingListDeleteView(View):
    @method_decorator(login_required(login_url='users:login_view'))
    @user_is_list_owner
    def post(self, request, pk):
        shopping_list = get_object_or_404(ShoppingList, pk=pk)
        shopping_list.delete()
        return redirect('lists:shopping_lists_archive_view')


class ArchiveShoppingListView(View):
    @method_decorator(login_required(login_url='users:login_view'))
    @user_is_list_owner
    def post(self, request, pk):
        shopping_list = get_object_or_404(ShoppingList, pk=pk)
        shopping_list.archived = True
        shopping_list.save()
        return redirect('lists:shopping_lists_view')


class MarkShoppingItemView(View):
    @method_decorator(login_required(login_url='users:login_view'))
    @user_is_list_owner_via_item
    def post(self, request):
        item_pk = int(request.POST.get('pk'))
        shopping_item = ShoppingItem.objects.get(pk=item_pk)

        if shopping_item.bought is False:
            shopping_item.bought = True
        else:
            shopping_item.bought = False
        shopping_item.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class AddShoppingListView(View):
    @method_decorator(login_required(login_url='users:login_view'))
    def get(self, request):
        list_create_form = ListCreateForm(None)
        template = 'lists/add_shopping_list.html'
        context = {
            'list_create_form': list_create_form,
        }
        return render(request, template, context)

    @method_decorator(login_required(login_url='users:login_view'))
    def post(self, request):
        list_create_form = ListCreateForm(request.POST)

        if list_create_form.is_valid():
            new_list = list_create_form.save(commit=False)
            new_list.user = request.user
            new_list.save()

            return redirect('lists:shopping_list_detail_view', pk=new_list.pk)

        template = 'lists/add_shopping_list.html'
        context = {
            'list_create_form': list_create_form,
        }
        return render(request, template, context)


class EditShoppingListView(UpdateView):
    model = ShoppingList
    form_class = ListCreateForm
    template_name = 'lists/edit_shopping_list.html'

    def get_queryset(self):
        qs = super(EditShoppingListView, self).get_queryset()
        return qs.filter(user=self.request.user)


class AddItemsToListView(View):
    @method_decorator(login_required(login_url='users:login_view'))
    @user_is_list_owner
    def get(self, request, pk):
        shopping_list = get_object_or_404(ShoppingList, pk=pk)
        template = 'lists/add_items_to_list.html'
        context = {
            'shopping_list': shopping_list,
        }
        return render(request, template, context)

    @method_decorator(login_required(login_url='users:login_view'))
    @user_is_list_owner
    def post(self, request, pk):
        shopping_list = get_object_or_404(ShoppingList, pk=pk)
        item_pk = request.POST.get('item-pk')
        item_name = request.POST.get('item-name')
        item = None

        # Checks if user adds predefined item
        try:
            item = Item.objects.get(pk=item_pk)
        except:
            pass

        # If user adds predefined item: creating or getting ShoppingItem
        # instance and adding foreignkey relation
        if item:
            obj, created = ShoppingItem.objects.get_or_create(
                    item=item, shopping_list=shopping_list)

        # Else creating or getting an custom ShoppingItem instance with no
        # relation to Item model
        else:
            obj, created = ShoppingItem.objects.get_or_create(
                    name=item_name, shopping_list=shopping_list)

            # Check if custom ShoppingItem instance exists in Item model.
            # If yes: creating relation with found Item instance.

            try:
                item = Item.objects.get(name=item_name)
                obj.item = item
                obj.save()
            except:
                pass

        # If object was already created: updating quantity.
        if not created:
            obj.quantity = obj.quantity + 1
            obj.save()

        return redirect('lists:add_items_to_list_view', pk=shopping_list.pk)


class DeleteItemsFromListView(View):
    @method_decorator(login_required(login_url='users:login_view'))
    @user_is_list_owner_via_item
    def post(self, request, pk):
        shopping_item = get_object_or_404(ShoppingItem, pk=pk)
        shopping_list = shopping_item.shopping_list
        shopping_item.delete()
        return redirect('lists:add_items_to_list_view',
                        pk=shopping_list.pk)


class EditItemsView(View):
    @method_decorator(login_required(login_url='users:login_view'))
    @user_is_list_owner_via_item
    def post(self, request):
        quantity = int(request.POST.get('quantity'))
        pk = int(request.POST.get('pk'))
        shopping_item = get_object_or_404(ShoppingItem, pk=pk)
        shopping_list = shopping_item.shopping_list
        shopping_item.quantity = quantity
        shopping_item.save()

        return redirect('lists:add_items_to_list_view',
                        pk=shopping_list.pk)

src/shopping/lists/templates/lists/add_items_js.html
<script>

(function() {

    var isMobile= {
        Android: function() {
            return navigator.userAgent.match(/Android/i);
        }
        ,
        BlackBerry: function() {
            return navigator.userAgent.match(/BlackBerry/i);
        }
        ,
        iOS: function() {
            return navigator.userAgent.match(/iPhone|iPad|iPod/i);
        }
        ,
        Opera: function() {
            return navigator.userAgent.match(/Opera Mini/i);
        }
        ,
        Windows: function() {
            return navigator.userAgent.match(/IEMobile/i);
        }
        ,
        any: function() {
            return (isMobile.Android() || isMobile.BlackBerry() || isMobile.iOS() || isMobile.Opera() || isMobile.Windows());
        }
    };

    $('#search-items').keyup(function(event) {
        var q = $(this).val(); 
        var key = event.which;
        if (key == 13) {
            $.ajax( {
                type: 'POST',
                url: '{% url "lists:add_items_to_list_view" pk=shopping_list.pk %}',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'item-name': q,
                }
                ,
                success: function(data) {
                    location.reload();
                }
                ,
                error: function(data) {
                    console.log('Ajax Error');
                }
            }
            );
        }
        
        $('.search-add').empty();
        
        if (q) {
            var submit_button = $('<button>').attr('class', 'form-control-feedback fui-plus');

            var csrf_token = $('<input>');
            csrf_token.attr('type', 'hidden').attr('name', 'csrfmiddlewaretoken').attr('value', '{{ csrf_token }}');

            var item_name = $('<input>');
            item_name.attr('type', 'hidden').attr('name', 'item-name').attr('value', q);

            var result = $('<form>').attr('action', '{% url "lists:add_items_to_list_view" pk=shopping_list.pk %}').attr('method', 'POST').append(item_name).append(csrf_token).append(q).append(submit_button);

            $('.search-add').append($('<li>').append(result));
        }

        $.ajax( {
            type: 'GET',
            url: '{% url "items:search_items_view" %}',
            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'q': q,
                'shopping_list_pk': '{{ shopping_list.pk }}',
            },
            success: function(data) {
                var new_list = $('<ul>').html(data);
                $('.search-result ul').eq(1).replaceWith(new_list);
            },
            error: function(data) {
                console.log('Ajax Error');
            }
        });
        
        
    });

    $('.quantity-select').click(function(event) {
        if(isMobile.any()) {
           $(this).val(''); 
        }
    }).change(function(event) {
        
        event.preventDefault();
        var quantity=$(this).val();
        var item_pk=$(this).attr('item-pk');

        $.ajax( {
            type: 'POST',
            url: '{% url "lists:edit_items_view" %}',
            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'quantity': quantity,
                'pk': item_pk
            }
            ,
            success: function(data) {
                console.log('Ajax Success');
            }
            ,
            error: function(data) {
                console.log('Ajax Error');
            }
        }
        );
    
    });
}

)();
</script>

src/shopping/lists/templates/lists/add_items_to_list.html
{% extends 'base.html' %} {% block head_title %}Add Items to {{ shopping_list.name }}{% endblock %} {% block content %} {% load staticfiles %}

<div class="add-items-list-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h6>Add Items to <a href="{% url 'lists:shopping_list_detail_view' pk=shopping_list.pk %}"><strong>{{ shopping_list.name }}</strong></a></h6>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="form-group">
                    <input type="text" value="" id="search-items" placeholder="Type here to search and add items" class="form-control" maxlength="30" />
                    <span class="form-control-feedback fui-search"></span>
                </div>
                <div class="search-result">
                    <ul class="search-add">
                    </ul>
                    <ul>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">

            </div>
        </div>
        <div class="row">
            <div class="col-xs-6">
                <p>Items in {{ shopping_list.name }}:</p>
            </div>
        </div>
        <div class="row">
            <ul>
                {% for shopping_item in shopping_list.shopping_items %}
                <li>
                    <div class="col-xs-6 item-name">
                        {{ shopping_item.name }}
                    </div>
                    <div class="col-xs-3">
                        <input type="number" class="form-control quantity-select" item-pk="{{ shopping_item.pk }}" value="{{ shopping_item.quantity }}">
                    </div>
                    <div class="col-xs-3">
                        <form method="POST" action="{% url 'lists:delete_items_from_list_view' pk=shopping_item.pk %}">
                            {% csrf_token %}
                            <div class="todo-right pull-right">
                                <button><span class="fui-trash"></span></button>
                            </div>
                        </form>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% include 'lists/add_items_js.html' %} {% endblock %}

src/shopping/lists/templates/lists/add_shopping_list.html
{% extends 'base.html' %} {% block head_title %}Add New List{% endblock %} {% block content %} {% load staticfiles %}

<div class="add-list-wrapper">
    <div class="container">
        <div class="row">
            <form class="add-list-form" method="POST">
                {% csrf_token %}
                <div class="col-sm-12">
                    <h6>Add New List</h6>
                </div>
                {% for field in list_create_form %}
                    {% if field.label == 'Date' %}
                    <div class="col-sm-12 col-md-6">
                        <div class="form-group input-group">
                            {{ field.errors }}
                            {{ field }}
                        </div>
                    </div>
                    {% else %}
                    <div class="col-sm-12 col-md-6">
                        <div class="form-group">
                            {{ field.errors }}
                            {{ field }}
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
                <div class="col-sm-12 text-center">
                    <button class="btn btn-embossed btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function() {
        var date_input_content = "<span class=\"input-group-addon fui-calendar\"></span>";

        $('.datepicker').parent().append(date_input_content);
        $('.datepicker').datepicker();
        $('.fui-calendar').click(function() {
            $('.datepicker').focus();
        });
    });
</script>

{% endblock %}

src/shopping/lists/templates/lists/shopping_list_detail.html
{% extends 'base.html' %} {% block head_title %}List {{ list.name }} {% endblock %} {% block content %} {% load staticfiles %}

<div class="detail-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-12 list-info">
                <h6>{{ shopping_list.name }}</h6>
                <p class="list-desc"><small>{{ shopping_list.shop }} at {{ shopping_list.date }}</small></p>
                <a href="{% url 'lists:edit_shopping_list_view' pk=shopping_list.pk %}" class="btn btn-block btn-primary btn-edit">Edit</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <select id="list-sort" class="form-control select select-primary select-block mbl">
                    <option value="pk">Sort by order of addition</option>
                    <option value="category">Sort by category</option>
                    <option value="name">Sort by name</option>
                    <option value="bought">Sort by bought</option>
                </select>
            </div>
            <div class="col-md-12 col-xs-12">
                <div class="todo list-items">
                    <ul>
                        {% for item in shopping_items %}
                        <li class="list-item {% if item.bought %} todo-done {% endif %}" list-item-pk="{{item.pk}}">
                            <div class="todo-icon fui-tag"></div>
                            <div class="todo-content">
                                <h4 class="todo-name">
                                    {{ item.name }}
                                </h4>
                                <strong>Quantity:</strong> {{ item.quantity }}
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- /.todo -->
            </div>
        </div>
        <a href="{% url 'lists:add_items_to_list_view' pk=shopping_list.pk %}">
            <div class="add-items-plus">
            </div>
        </a>
    </div>
</div>

{% include 'lists/shopping_list_detail_js.html' %}

{% endblock %}

src/shopping/lists/templates/lists/shopping_lists.html
{% extends 'base.html' %} {% block head_title %}My Shopping Lists {% endblock %} {% block content %} {% load staticfiles %}

<div class="lists-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h6>My Lists</h6>
            </div>
          
            <div class="col-md-12">
                <ul class="lists-list">
                    {% for list in shopping_lists %}
                    <li>
                        <a href="{% url 'lists:shopping_list_detail_view' pk=list.pk %}">
                        <div class="todo-icon fui-list"></div>
                        <div class="todo-content">
                            <h4 class="todo-name">
                                <strong>{{ list.name }}</strong> in {{ list.shop }}
                            </h4>
                            <small>{{ list.date }}</small>
                        </div>
                        </a>
                        <form method="POST" action="{% url 'lists:archive_shopping_list_view' pk=list.pk %}">
                            {% csrf_token %}
                            <div class="todo-right pull-right">
                                <button><span class="fui-cross-circle"></span></button>
                            </div>
                        </form>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <a href="{% url 'lists:add_shopping_list_view' %}">
            <div class="add-items-plus">
            </div>
        </a>
    </div>
</div>

{% include 'lists/shopping_lists_js.html' %}

{% endblock %}

src/shopping/lists/templates/lists/shopping_lists_archive.html
{% extends 'base.html' %} {% block head_title %}Archived Shopping Lists {% endblock %} {% block content %} {% load staticfiles %}

<div class="lists-wrapper archive">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h6>Archived Lists</h6>
                <p class="list-desc"><small>Go to <strong><a href="{% url 'lists:shopping_lists_view' %}">My Lists</a></strong> to archive your lists.</small></p>
            </div>
            <div class="col-md-12">
                <ul class="lists-list">
                    {% for list in shopping_lists %}
                    <li>
                        <a href="{% url 'lists:shopping_list_detail_view' pk=list.pk %}">
                        <div class="todo-icon fui-list"></div>
                        <div class="todo-content">
                            <h4 class="todo-name">
                                <strong>{{ list.name }}</strong> in {{ list.shop }}
                            </h4>
                            <small>{{ list.date }}</small>
                        </div>
                        </a>
                        <form method="POST" action="{% url 'lists:shopping_list_delete_view' pk=list.pk %}">
                            {% csrf_token %}
                            <div class="todo-right pull-right">
                                <button><span class="fui-trash"></span></button>
                            </div>
                        </form>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% include 'lists/shopping_lists_js.html' %}

{% endblock %}

src/shopping/lists/templates/lists/shopping_lists_js.html
<script>
    (function(){
        $(window).load(function(){
            $('.lists-list > li').each(function(i){
                setTimeout(function(){
                    $('.lists-list > li').eq(i).css({
                        'opacity': 1,
                        'transform': 'translateY(0px)'
                    });
                }, i*100);
            });
        });
    })();
</script>

src/shopping/lists/templates/lists/shopping_lists_search.html
{% extends 'base.html' %} {% block head_title %}Search results{% endblock %} {% block content %} {% load staticfiles %}

<div class="lists-wrapper search-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h6>Search Results</h6>
            </div>
          
            <div class="col-md-12">
                <ul class="lists-list">
                    {% for list in shopping_lists %}
                    <li>
                        <a href="{% url 'lists:shopping_list_detail_view' pk=list.pk %}">
                        <div class="todo-icon fui-list"></div>
                        <div class="todo-content">
                            <h4 class="todo-name">
                                <strong>{{ list.name }}</strong> in {{ list.shop }}
                            </h4>
                            <small>{{ list.date }}</small>
                        </div>
                        </a>
                        <form method="POST" action="{% url 'lists:archive_shopping_list_view' pk=list.pk %}">
                            {% csrf_token %}
                            <div class="todo-right pull-right">
                                <button><span class="fui-cross-circle"></span></button>
                            </div>
                        </form>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>


{% endblock %}