src/shopping/main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.MainPageView.as_view(), name='main_page_view'),
]

src/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^lists/', include('lists.urls', namespace="lists")),
    url(r'^items/', include('items.urls', namespace="items")),
    url(r'^charts/', include('charts.urls', namespace="charts")),
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace="main")),
    url(r'^api/lists/', include('lists.api.urls', namespace="lists_api")),
    url(r'^api/items/', include('items.api.urls', namespace="items_api")),
    url(r'^api/charts/', include('charts.api.urls', namespace="charts_api")),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shopping/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='login_view'),
    url(r'^register/$', views.RegisterView.as_view(), name='register_view'),
    url(r'^change-password/$', views.ChangePasswordView.as_view(),
        name='change_password_view'),
    url(r"^logout/$", auth_views.logout_then_login, name="logout_view"),
]

src/shopping/users/forms.py
from django.contrib.auth.forms import (
    PasswordChangeForm,
    UserCreationForm
)
from django.contrib.auth.models import User
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
                               label="Username", max_length=30,
                               widget=forms.TextInput(attrs={
                                    'placeholder': 'Enter Your Name',
                                    'class': 'form-control login-field',
                                    'name': 'username'
                                    })
                               )
    password = forms.CharField(
                               label="Password",
                               max_length=30,
                               widget=forms.TextInput(attrs={
                                    'placeholder': 'Password',
                                    'class': 'form-control login-field',
                                    'name': 'password',
                                    'type': 'password'
                                    })
                               )


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
    
    username = forms.CharField(
                               label="Username", max_length=30,
                               widget=forms.TextInput(attrs={
                                    'placeholder': 'Enter Your Name',
                                    'class': 'form-control login-field',
                                    'name': 'username'
                                    })
                               )
    password1 = forms.CharField(
                               label="Password",
                               max_length=30,
                               widget=forms.TextInput(attrs={
                                    'placeholder': 'Password',
                                    'class': 'form-control login-field',
                                    'name': 'password1',
                                    'type': 'password'
                                    })
                               )
    password2 = forms.CharField(
                               label="Confirm Password",
                               max_length=30,
                               widget=forms.TextInput(attrs={
                                    'placeholder': 'Confirm Password',
                                    'class': 'form-control login-field',
                                    'name': 'password2',
                                    'type': 'password'
                                    })
                               )
    email = forms.EmailField(
                               label="E-mail", max_length=30,
                               widget=forms.TextInput(attrs={
                                    'placeholder': 'E-mail',
                                    'class': 'form-control login-field',
                                    'name': 'username'
                                    })
                               )
                               
    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email) \
                                 .exclude(username=username).exists():
            raise forms.ValidationError(u'This e-mail already exists in the database')
        return email


class PasswordChangeCustomForm(PasswordChangeForm):
    old_password = forms.CharField(
                                   label="Password",
                                   max_length=30,
                                   widget=forms.TextInput(attrs={
                                        'placeholder': 'Old Password',
                                        'class': 'form-control login-field',
                                        'type': 'password'
                                        })
                                   )
    new_password1 = forms.CharField(
                                   label="Password",
                                   max_length=30,
                                   widget=forms.TextInput(attrs={
                                        'placeholder': 'Password',
                                        'class': 'form-control login-field',
                                        'type': 'password'
                                        })
                                   )
    new_password2 = forms.CharField(
                                   label="Confirm Password",
                                   max_length=30,
                                   widget=forms.TextInput(attrs={
                                        'placeholder': 'Confirm Password',
                                        'class': 'form-control login-field',
                                        'type': 'password'
                                        })
                                    )

src/shopping/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.models import User

from .forms import LoginForm, RegisterForm, PasswordChangeCustomForm


class LoginView(View):
    template = 'users/login.html'

    def get(self, request):
        login_form = LoginForm(None)
        context = {
            'login_form': login_form,
        }
        return render(request, self.template, context)

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('main:main_page_view')
                else:
                    messages.error(request,
                                   'User {} has been blocked'.format(username),
                                   extra_tags='login')
            else:
                messages.error(request, 'Incorrect password and/or username',
                               extra_tags='login')
        context = {
            'login_form': login_form,
        }
        return render(request, self.template, context)


class RegisterView(View):
    template = 'users/register.html'

    def get(self, request):
        register_form = RegisterForm(None)
        context = {
            'register_form': register_form,
        }
        return render(request, self.template, context)

    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            password = register_form.cleaned_data['password1']
            email = register_form.cleaned_data['email']
            user = register_form.save(commit=False)
            user.email = email
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('main:main_page_view')

        context = {
            'register_form': register_form,
        }
        return render(request, self.template, context)


class ChangePasswordView(View):
    template = 'users/password_change.html'

    def get(self, request):
        password_change_form = PasswordChangeCustomForm(None)
        context = {
            'password_change_form': password_change_form,
        }
        return render(request, self.template, context)

    def post(self, request):
        password_change_form = PasswordChangeCustomForm(user=request.user,
                                                        data=request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Password has been changed!',
                             extra_tags='password')
            return redirect('main:main_page_view')

        context = {
            'password_change_form': password_change_form
        }
        return render(request, self.template, context)

src/shopping/users/templates/users/login.html
{% extends 'base.html' %} 
{% load staticfiles %}
{% block head_title %}Login{% endblock %}
{% block wrapper %}
<div class="login-screen">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="login-icon">
                    <img src="{% static 'img/icons/png/Pocket.png' %}" alt="Welcome to Mail App" />
                    <h4>Welcome to <span class="logo">Lister</span></h4>
                </div>
            </div>
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                <form class="login-form" method="POST">
                    {% csrf_token %}
                    {% for message in messages %}
                        {% if "login" in message.tags %}
                            <div class="alert alert-danger">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                    <div class="form-group">
                        {{ login_form.username }}
                        <label class="login-field-icon fui-user" for="login-name"></label>
                    </div>
                    <div class="form-group">
                        {{ login_form.password }}
                        <label class="login-field-icon fui-lock" for="login-pass"></label>
                    </div>

                    <button class="btn btn-primary btn-lg btn-block" type="submit">Log in</button>
                    <a class="login-link" href="{% url 'users:register_view' %}">Register</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/shopping/users/templates/users/password_change.html
{% extends 'base.html' %} 
{% block head_title %}Change Password{% endblock %}
{% load staticfiles %} {% block wrapper %}
<div class="login-screen">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="login-icon">
                    <img src="{% static 'img/icons/png/Pocket.png' %}" alt="Welcome to Mail App" />
                    <h4>Welcome to <span class="logo">Lister</span></h4>
                </div>
            </div>
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                {{ password_change_form.non_field_errors }}
                <form class="login-form" method="POST">
                    {% csrf_token %}
                    {% for field in password_change_form %}
                        {{ field.errors }}
                            <div class="form-group">
                        {{ field }}
                        {% if field.label == "Username" %}
                            <label class="login-field-icon fui-user" for="login-name"></label>
                        {% endif %}
                        {% if field.label == "Password" or field.label == "Confirm Password" %}
                            <label class="login-field-icon fui-lock" for="login-pass"></label>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Change Password</button>
                    <a class="login-link" href="{% url 'main:main_page_view' %}">Back to main page</a>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

src/shopping/users/templates/users/register.html
{% extends 'base.html' %} 
{% block head_title %}Register{% endblock %}
{% load staticfiles %} {% block wrapper %}
<div class="login-screen">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="login-icon">
                    <img src="{% static 'img/icons/png/Pocket.png' %}" alt="Welcome to Mail App" />
                    <h4>Welcome to <span class="logo">Lister</span></h4>
                </div>
            </div>
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                {{ register_form.non_field_errors }}
                <form class="login-form" method="POST">
                    {% csrf_token %}
                    {% for field in register_form %}
                        {{ field.errors }}
                            <div class="form-group">
                        {{ field }}
                        {% if field.label == "Username" %}
                            <label class="login-field-icon fui-user" for="login-name"></label>
                        {% endif %}
                        {% if field.label == "Password" or field.label == "Confirm Password" %}
                            <label class="login-field-icon fui-lock" for="login-pass"></label>
                        {% endif %}
                        {% if field.label == "E-mail" %}
                            <label class="login-field-icon fui-mail" for="login-name"></label>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Register</button>
                    <a class="login-link" href="{% url 'users:login_view' %}">Login</a>
                </form>
            </div>



        </div>
    </div>

</div>
{% endblock %}