src/shopping/main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.MainPageView.as_view(), name='main_page_view'),
]

src/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^lists/', include('lists.urls', namespace="lists")),
    url(r'^items/', include('items.urls', namespace="items")),
    url(r'^charts/', include('charts.urls', namespace="charts")),
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace="main")),
    url(r'^api/lists/', include('lists.api.urls', namespace="lists_api")),
    url(r'^api/items/', include('items.api.urls', namespace="items_api")),
    url(r'^api/charts/', include('charts.api.urls', namespace="charts_api")),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shopping/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Adrian Dworanowski">
        
        <title>LISTER - Shopping List App - {% block head_title %}{% endblock %}</title>
        
        {% include 'css.html' %}
        {% include 'pre-js.html' %}
    </head>
    
    <body>
        {% block wrapper %}
        
            {% include 'navbar.html' %}
            
            {% block content %} 
            {% endblock %}
            
        {% endblock %}
        
        {% include 'post-js.html' %}
    </body>
</html>

src/shopping/templates/css.html
{% load staticfiles %}

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Molle:400i" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" rel="stylesheet">
<link href="{% static 'css/flat-ui.css' %}" rel="stylesheet">
<link href="{% static 'css/custom.css' %}" rel="stylesheet">

src/shopping/templates/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-inverse navbar-embossed navbar-fixed-top navbar-custom" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
            <span class="sr-only">Toggle navigation</span>
            </button>
            <a class="navbar-brand" href="{% url 'main:main_page_view' %}">Lister</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-01">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage Lists <b class="caret"></b></a>
                  <span class="dropdown-arrow"></span>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'lists:shopping_lists_view' %}">My Lists</a></li>
                    <li><a href="{% url 'lists:add_shopping_list_view' %}">Add List</a></li>
                    <li><a href="{% url 'lists:shopping_lists_archive_view' %}">Archive</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'charts:bought_items_chart_view' %}">Charts</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">User Actions <b class="caret"></b></a>
                  <span class="dropdown-arrow"></span>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'users:change_password_view' %}">Change Password</a></li>
                    <li><a href="{% url 'users:logout_view' %}?next={{request.path}}">Logout</a></li>
                  </ul>
                </li>
            </ul>
            
            <a href="{% url 'users:logout_view' %}?next={{request.path}}" class="pull-right nav-logout"><span class="fui-exit"></span></a>
            <form class="navbar-form navbar-right" action="{% url 'lists:shopping_lists_search_view' %}" role="search">
                <div class="form-group">
                    <div class="input-group">
                        <input class="form-control" id="navbarInput-01" type="search" name="q" placeholder="Search">
                        <span class="input-group-btn">
                    <button type="submit" class="btn"><span class="fui-search"></span></button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.navbar-collapse -->
    </div>

</nav>
<!-- /navbar -->

src/shopping/templates/post-js.html
{% load staticfiles %}

<script src="{% static 'js/application.js' %}"></script>
<script src="{% static 'js/prettify.js' %}"></script>

<script>
    (function() {
        $('.list-item').click(function(event) {
            var item_pk = $(this).attr("list-item-pk");

            $.ajax({
                type: 'POST',
                url: '{% url "lists:mark_shopping_item_view" %}',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'pk': item_pk
                },
                success: function(data){
                    console.log('Ajax Success');
                    $(this).toggleClass('todo-done');
                },
                error: function(data) {
                    console.log('Ajax Error');
                }
            });
        });

    })();
</script>

src/shopping/templates/pre-js.html
{% load staticfiles %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

<script src="{% static 'js/flat-ui.js' %}"></script>