src/shopping/charts/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ShoppingItemsCountsAPIView.as_view(),
            name="shopping_items_counts_api_view"),
]

src/shopping/charts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.BoughtItemsChartView.as_view(),
            name="bought_items_chart_view"),
]

src/shopping/main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.MainPageView.as_view(), name='main_page_view'),
]

src/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^lists/', include('lists.urls', namespace="lists")),
    url(r'^items/', include('items.urls', namespace="items")),
    url(r'^charts/', include('charts.urls', namespace="charts")),
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace="main")),
    url(r'^api/lists/', include('lists.api.urls', namespace="lists_api")),
    url(r'^api/items/', include('items.api.urls', namespace="items_api")),
    url(r'^api/charts/', include('charts.api.urls', namespace="charts_api")),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shopping/charts/models.py
from django.db import models

# Create your models here.

src/shopping/charts/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response

from .utils import filter_by_time_period, get_ordered_data

from lists.models import ShoppingList, ShoppingItem


class ShoppingItemsCountsAPIView(APIView):
    def get(self, request):
        time_period = request.GET.get('time-period')

        # Checking for time period. If true: returning queryset filtered by 
        # date and user.
        if time_period:
            shopping_lists = filter_by_time_period(self.request, time_period)
        else:
            shopping_lists = ShoppingList.objects \
                .filter(user=self.request.user)

        # Getting ordered dictionary with shopping item names and quantities.
        # Ordered by quantity descending
        ordered_data = get_ordered_data(shopping_lists)

        # Creating lists of item's labels and values. Returns 10 most
        # popular items.
        labels = [key for key in ordered_data.keys()][:10]
        values = [value for value in ordered_data.values()][:10]

        response = {
            'labels': labels,
            'values': values
        }
        
        # Pushing response to chart app front-end.
        return Response(response)

src/shopping/charts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View


class BoughtItemsChartView(View):
    def get(self, request):
        template = 'charts/category_chart.html'
        context = {}
        return render(request, template, context)

src/shopping/charts/templates/charts/category_chart.html
{% extends 'base.html' %} {% block head_title %}Charts{% endblock %} {% block content %} {% load staticfiles %}
<div class="charts-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h6>Charts</h6>
                <p class="list-desc"><small>Items you bought, all in one place.</small></p>
            </div>
            <div class="col-sm-12">
                <select id="time-select" class="form-control select select-primary select-block mbl">
                    <option value="">All Bought Items</option>
                    <option value="last-month">Bought Last Month</option>
                    <option value="last-year">Bought Last Year</option>
                </select>
            </div>
            <div class="col-sm-12">
                <canvas id="category-chart"></canvas>
            </div>
        </div>
    </div>
</div>
{% include 'charts/category_chart_js.html' %} {% endblock %}

src/shopping/charts/templates/charts/category_chart_js.html
<script>
    (function() {
        var time_period;

        var chart_init = function(){
            var labels = [];
            var values = [];
            
            $.ajax({
                type: 'GET',
                url: '{% url "charts_api:shopping_items_counts_api_view" %}',
                data: {
                        'time-period': time_period
                },
                success: function(data) {
                    labels = data.labels;
                    values = data.values;
                    
                    var ctx = document.getElementById('category-chart').getContext('2d');
                    var chart = new Chart(ctx, {
                        // The type of chart we want to create
                        type: 'doughnut',
    
                        // The data for our dataset
                        data: {
                            labels: labels,
                            datasets: [{
                                label: "Shopping Items",
                                backgroundColor: [
                                    '#1ABC9C',
                                    '#2ECC71',
                                    '#3498DB',
                                    '#9B59B6',
                                    '#34495E',
                                    '#F1C40F',
                                    '#E67E22',
                                    '#E74C3C',
                                    '#7F8C8D',
                                    '#BDC3C7'
                                ],
                                // borderColor: 'rgb(255, 99, 132)',
                                data: values,
                            }]
                        },
                        // Configuration options go here
                        options: {
                            responsive: true
                        }
                    });
                }
            });
        };
        
        chart_init();
        
        $('#time-select').change(function(event){
            time_period = $(this).val();
            $('#category-chart').siblings().remove();
            chart_init();
        });

    })();
</script>